name: Nightly Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use"
        required: true
        default: "master"

jobs:
  nightly_ub:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [release, debugoptimized]

    steps:
      - name: Run tests
        run: |
          ulimit -c unlimited 
          ls -al /var/log/
          cat /var/log/kern.log
          ls -al /var/lib/systemd/coredump/

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-artifact-ubuntu-${{ matrix.build_type }}
          path: |
            builddir/meson-logs/
            /var/log/syslog
            /cores
